### PR TITLE
Display when the ticker is being updated and when the last update happened

### PR DESCRIPTION
**Pull request by BitcoinMitchell**
The title pretty much says it all, doesn't it. 😉

### CODE REVIEW

**Comment by BitcoinMitchell** [comment]
Maybe we should make this an option, since I'm not sure if everyone would appreciate it. :thinking:

**Comment by AIFanatic** [comment]
Thank you for this much needed feature.

In the future and with the battery coming the time may need to be re-positioned.
Also would be great to use some service similar to the "live-checker" to get the user timezone and display the time accordingly but I will create a separate issue for that.

**Comment by BitcoinMitchell** [comment]
Most welcome! I tried to think of a simple solution for the timezone issue, but gave up after a while.

**Comment by AIFanatic** [comment]
Forgot to point out:

```
    String last_update = ticker["last_update"] != "0" ? Utils::readableTimestamp(ticker["last_update"]) : "Never";
    ...
    manager->render->drawText(0, 10, ticker["last_update"] != "0" ? last_update.c_str() : "Never", 7, BLACK, RIGHT_ALIGNMENT);
```

Isn't the second inline if statement redundant?

**Comment by ping-localhost** [comment]
Yes, yes it is. Totally forgot to refactor that. Will send a patch in a bit. :wink:

**Comment by BitcoinMitchell** [comment]
Yes, my bad. I've opened a PR to resolve this: #30.

**Pull request merged**
